"""sync models after relationship refactor

Revision ID: 5f36aec5e08c
Revises: 7bcf9dad38d4
Create Date: 2025-10-28 10:58:40.623164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f36aec5e08c'
down_revision: Union[str, Sequence[str], None] = '7bcf9dad38d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
